apiVersion: apps/v1
kind: Deployment
metadata:
  name: inv-app-deployment
  labels:
    app: inv-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inv-app
  template:
    metadata:
      labels:
        app: inv-app
    spec:
      containers:
        - name: invk8-app-container
          image: shopyeebee-invservice:1.0
          ports:
            - containerPort: 8080
