apiVersion: v1
kind: Service
metadata:
  name: invk8-nodeport-service
spec:
  type: NodePort
  selector:
    app: inv-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
